name: Tailwind deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
    paths:
      - 'tailwind/**'
  #pull_request:
  #  types:
  #    - closed
  #  branches:
  #    - master

jobs:
  #if_merged:
  #  if: github.event.pull_request.merged == true
  Tailwind-Deploy:
    name: 🎉 Tailwind Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          # ARGS: "-rltgoDzvO --delete"
          REMOTE_HOST: 145.79.3.173
          REMOTE_USER: u965251139
          REMOTE_PORT: "65002"
          TARGET: domains/ableproadmin.com/public_html/tailwind/free
          EXCLUDE: "/tailwind/node_modules/"
